### PR TITLE
Add support for .lz4 extension to file-roller

### PR DESCRIPTION
**Pull request by BenWiederhake**

### CODE REVIEW

**Comment by BenWiederhake** [comment]
The tests for `DIST=fedoradev` have been failing for all the previous PRs, too, so I claim that it's not my fault.

**Comment by scop** [comment]
Thanks!

**Comment by BenWiederhake** [comment]
Do you know how to poke the Debian packagers?  The last upload there was April 2016, their git repo is dead, and their IRC chat is dead, too.  I don't just want to randomly spam their email inboxes.

**Comment by scop** [comment]
The best/only contact I know of is dapal@debian, and he's also a collaborator here. I believe he's been busy with other things for past few years, and perhaps it would be a good idea to try and find a new maintainer who has more time available for the Debian package.

**Pull request merged**
