### PR TITLE
Add initial simple completion of p11-kit command

### PR DESCRIPTION
**Pull request by Jakuje**
Simple bash completion for p11-kit commands:

https://github.com/p11-glue/p11-kit/

### CODE REVIEW

**Comment by Jakuje** [comment]
ping. Any progress on this? The build failure does not look related to my changes if I see right.

**Comment by scop** [comment]
No progress yet, at least from me. As mentioned in CONTRIBUTING.md, have you thought about submitting this to upstream p11-glue? They seem to be using autotools and we have easy to use autotools recipe for installing completions, see README.md.

**Comment by Jakuje** [comment]
Thank you for the pointer and sorry I missed that part. I am checking with the p11-kit maintainer:

https://github.com/p11-glue/p11-kit/pull/258

**Comment by scop** [comment]
No problem, thanks for considering. Posted a comment there.

**Comment by Jakuje** [comment]
Closing as the p11-glue/p11-kit#258 got merged.

**Pull request closed without merging**
