### PR TITLE
chore: Quote changelog lines with `$.*{.*$`

### PR DESCRIPTION
**Pull request by yedayak**
See https://github.com/scop/bash-completion/issues/1272

### CODE REVIEW

**Review by akinomyoga — APPROVED** [review]
There are still other occurrences of raw `$`, which might better be quoted too for consistency, but it is not a big problem.

The CI error is caused by the change in #1090, which slipped off from the check due to some setup changes.

**Comment by akinomyoga** [comment]
I guess the CI error should be fixed first in a separate PR.

**Comment by yedayak** [comment]
> I guess the CI error should be fixed first in a separate PR.

Yeah, made https://github.com/scop/bash-completion/pull/1274

**Comment by akinomyoga** [comment]
Can you rebase it to rerun the CI?

**Comment by yedayak** [comment]
> Can you rebase it to rerun the CI?

Done

**Comment by scop** [comment]
No problem with merging this, but as a sustainable solution, I'd rather have release-please (or our use of it) fixed to prevent issues like this, if possible.

**Pull request merged**
