### PR TITLE
Explicitly specify `unset` types / Adjust uses of temporary global variables

### PR DESCRIPTION
**Pull request by akinomyoga**
I describe the detail in the commit message of each commit.

### CODE REVIEW

**Comment by akinomyoga** [comment]
In my local environment, `pre-commit` hook produces the following `mypy` error (even though the `mypy` test succeeds on CI). Do you know how to resolve the error. I'm now turning off the pre-commit hook because of this error.

```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

Success: no issues found in 4 source files
Success: no issues found in 4 source files
test/t/unit/test_unit_xinetd_services.py:3: error: Cannot find implementation or library stub for module named "conftest"  [import]
test/t/unit/test_unit_expand_tilde_by_ref.py:3: error: Cannot find implementation or library stub for module named "conftest"  [import]
test/t/unit/test_unit_init_completion.py:3: error: Cannot find implementation or library stub for module named "conftest"  [import]
test/t/unit/test_unit_quote_readline.py:5: error: Cannot find implementation or library stub for module named "conftest"  [import]
test/t/unit/test_unit_quote_readline.py:5: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 4 errors in 4 files (checked 4 source files)
test/t/unit/test_unit_pids.py:3: error: Cannot find implementation or library stub for module named "conftest"  [import]
test/t/unit/test_unit_known_hosts_real.py:5: error: Cannot find implementation or library stub for module named "conftest"  [import]
test/t/unit/test_unit_known_hosts_real.py:5: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 2 errors in 2 files (checked 2 source files)
```

**Comment by scop** [comment]
LGTM, merging.

I'll have a look at the mypy check now, let'see if I can come up with something useful.

**Comment by scop** [comment]
> I'll have a look at the mypy check now, let'see if I can come up with something useful.

#605, hopefully useful :)

**Comment by akinomyoga** [comment]
Thank you!

**Pull request merged**
