### PR TITLE
Update README.md distinguishing often vs. not

### PR DESCRIPTION
**Pull request by jidanni**

### CODE REVIEW

**Review by akinomyoga — APPROVED** [review]
LGTM

**Comment by akinomyoga** [comment]
@jidanni Can you update the commit message? We require it to be in the format specified by [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).

**Comment by jidanni** [comment]
OK, here you go:
>fix: distinguish often vs. not

Please insert it for me. I have bad luck editing edits here on github.com. Thanks!

**Comment by scop** [comment]
Added with `docs(README`; `fix` is for software fixes. Thanks!

**Pull request merged**
