### PR TITLE
ethtool: New completion

### PR DESCRIPTION
**Pull request by kevinoid**
This commit adds completion for [ethtool](https://kernel.org/pub/software/network/ethtool/), "the standard Linux utility for controlling network drivers and hardware".

Some tests require the fix from #288 due to line wrapping for some completions.

Thanks for considering,
Kevin

### CODE REVIEW

**Comment by kevinoid** [comment]
Rebased onto `master` now that #288 has been merged.

**Comment by kevinoid** [comment]
Thanks for the feedback!

I will ask the ethtool maintainers if they would be interested in shipping the bash completion script with ethtool and follow-up with their response.

**Comment by kevinoid** [comment]
This bash-completion script [will be included in the next ethtool release](https://lore.kernel.org/netdev/20190424195428.GA16350@tuxdriver.com/).  No need to ship it in bash-completion.  Thanks again for reviewing it and the suggestion to submit it upstream.

**Comment by scop** [comment]
Awesome, thanks!

**Pull request closed without merging**
