### PR TITLE
[WIP] Improve p4 completion

### PR DESCRIPTION
**Pull request by zachwhaley**
- Supports Perforce 2015.2 commands
- Complete global options
- Complete command options, including multi-parameter options, like -dup
- Complete file revisions to an extent

I need to add testing.
Please provide feedback!

### CODE REVIEW

**Comment by scop** [comment]
I'm afraid reviewing and feedback for changes this large will require help from someone who actually has access to and uses p4 for something. I'm not sure even how I would go about starting to test, assuming the test cases existed...

**Comment by zachwhaley** [comment]
Yeah, I was afraid of that.  I know some of the p4 devs are active on Twitter.  I might see if any of them would want to test this.

In the mean time, I'll work on writing tests in y'alls test suite.

**Comment by scop** [comment]
Just an idea, perhaps the p4 folks would be interested in adopting the completion with the product itself, or contribs of some sort if it has one, or something like that?

**Comment by lizlam** [comment]
@zachwhaley Wow! This is very thorough and complete (no pun intended 😄 )  What do you need to get the pull request accepted?  Do you just need it tested?  Also I can post on the p4 community Slack channel and see if others can help.

**Comment by scop** [comment]
My first preference would be to have this shipped somewhere outside bash-completion altogether, see my previous comment -- any thoughts on that? Having completions that we (== currently sadly "I") cannot sanely test automatically (nor possibly even manually!) and that have no active users maintaining them is not good.

**Comment by zachwhaley** [comment]
That makes sense.

Thanks for the advice :smile:

**Comment by scop** [comment]
Note that my opinion applies to the current p4 completion included with bash-completion as well; I'd gladly drop it if a better and maintained one was available somewhere else. If you do get yours included somewhere, let me know?

**Comment by zachwhaley** [comment]
Thanks again!

I've got the script on GitHub currently, and I'll see what can be done with the Perforce folks.

https://github.com/zachwhaley/p4-completion

**Pull request closed without merging**
