### PR TITLE
feat: more fallback 3rd party completion loaders

### PR DESCRIPTION
**Pull request by scop**
Mainly from https://github.com/spf13/cobra/blob/main/projects_using_cobra.md

### CODE REVIEW

**Review by akinomyoga — APPROVED** [review]
> Mainly from https://github.com/spf13/cobra/blob/main/projects_using_cobra.md

Maybe we can mention this link somewhere in our documentation (or wiki), so we can track the changes in the linked page.

**Comment by scop** [comment]
Sure, added https://github.com/scop/bash-completion/wiki/Externally-available-completions/_compare/61f7f9843c340613b3a13ab57e70d9614bb7ce8d...a4e3e6f0e899a06b1bb534cd1ab9158fe77da63a for general considerations about the external completion page and 3rd party fallbacks, and the link in https://github.com/scop/bash-completion/wiki/Externally-available-completions/_compare/a4e3e6f0e899a06b1bb534cd1ab9158fe77da63a...8a638f545ea707fbaeecdffbe5aab6df8e49a09d.

**Comment by scop** [comment]
Oh, forgot to mention that removing entries having 3rd party loaders from the external completions page loses the info whether the completions require bash-completion or not. In that sense I'm open to reverting the first change as well as keeping it, dunno which way I'd prefer :shrug: (feel free to modify the way you see fit)

**Comment by akinomyoga** [comment]
Thank you. I think it is also good to keep the existing version information, (though I'm not sure if it will actually be used in the future so I think we do not have to collect the information actively).
- I added a separate section: [wiki - Externally-available-completions - 8a638f54...c4e651fe](https://github.com/scop/bash-completion/wiki/Externally-available-completions/_compare/8a638f545ea707fbaeecdffbe5aab6df8e49a09d...c4e651fe3490667cf52dd87f932a1d617615b78d)

**Comment by scop** [comment]
Thanks!

**Pull request merged**
