### PR TITLE
curl: fix option listing in newer versions

### PR DESCRIPTION
**Pull request by algorythmic**
`_parse_help` only takes a single parameter (which is then splits) for the options that it invokes the tool with, so `curl` was being invoked with just `--help`, not with `--help all`.

### CODE REVIEW

**Comment by algorythmic** [comment]
The test failure seems unrelated, is there something else I should do here?

**Comment by danyspin97** [comment]
Hi! Any update on this PR?

**Comment by akinomyoga** [comment]
I need this change before performing the interface change of `_parse_help`.

**Review by scop — APPROVED** [review]
Cheers, added the requested test case, I'm good with merging this if/when it passes CI.

**Comment by akinomyoga** [comment]
Thank you for adding the test!

**Review by akinomyoga — APPROVED** [review]

**Pull request merged**
