### PR TITLE
Add support for Include in ssh config (#70)

### PR DESCRIPTION
**Pull request by edlmo**
This patch adds support for the Include directive in _ssh_config_ files (issue #70).
It adds the included (readable) files to the `config` variable to be later processed by the `_known_hosts_real()` function.

### CODE REVIEW

**Comment by edlmo** [comment]
Agree with the function name, it could be `_included_ssh_config_files`.

But I'm not so sure about moving that functionality inlined on `_known_hosts_real`. The ssh config allows to use the Include directive inside the included files... so the recursive function seems to be a good approach to me.

If you are ok with that I could change the function name and look into the  test cases.

PD: thanks to you for bash-completion ;)

**Comment by scop** [comment]
Ah, I somehow missed that the includes and the function is recursive. In that case, agreed with the current approach.

**Comment by edlmo** [comment]
I've added a test case for the ssh_config Include functionality (fixing some bugs along the way).

**Comment by scop** [comment]
LGTM, thanks

**Pull request merged**
